added edit feature to recommendation list
AY2021S2-CS2113T-F08-3/tp pull request #78
Opened 2021-03-30 11:25 UTC by Krithigha24

fixes #63

2021-03-30 16:13 UTC, huachen24 requested changes

2021-03-30 16:13 UTC, huachen24 commented on src/main/java/seedu/connoisseur/commands/RecommendationList.java
> +        Ui ui = new Ui();
try to use the existing ui instance

2021-03-31 03:39 UTC, Krithigha24 commented on src/main/java/seedu/connoisseur/commands/RecommendationList.java
> +        Ui ui = new Ui();
edited accordingly!

2021-03-31 04:26 UTC, huachen24 approved these changes

2021-03-31 04:26 UTC, merged